[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[dependencies]
utf8-chars = "3.0.3"
reset_iterator = { path = "../reset_iterator" }
thiserror = "1.0.63"
miette = { version = "7.2.0", features = ["fancy"] }
